import { useEffect, useState } from 'react'
import './Middleman.css'

type MiddlemanUser = { username: string; email: string; avatar: string; createdAt: string; role: string }
type Stats = { pendingRequests: number; activeTransactions: number; completedTransactions: number; openDisputes: number }

export function MiddlemanDashboard({ user, onLogout }: { user: MiddlemanUser; onLogout: () => void }) {
  const [stats, setStats] = useState<Stats>({ pendingRequests: 0, activeTransactions: 0, completedTransactions: 0, openDisputes: 0 })
  const [section, setSection] = useState('Overview')
  useEffect(() => { fetch('/api/middleman/me').then((response) => response.json()).then((data) => data.stats && setStats(data.stats)).catch(() => undefined) }, [])
  const items = ['Overview', 'Requests', 'Active Transactions', 'Completed', 'Disputes', 'Messages', 'Customers', 'Audit Logs', 'Settings']
  return <div className="middleman-dashboard"><aside className="mm-sidebar"><div className="brand"><span className="brand-mark">G</span><span>GAME<span>GUARD</span></span></div><p className="mm-label">MIDDLEMAN WORKSPACE</p><nav>{items.map((item) => <button className={section === item ? 'mm-nav active' : 'mm-nav'} onClick={() => setSection(item)} key={item}><span>{['▦', '⊙', '↔', '✓', '!', '□', '◎', '≡', '⚙'][items.indexOf(item)]}</span>{item}</button>)}<button className="mm-nav" onClick={onLogout}><span>↪</span>Logout</button></nav><div className="mm-user"><div className="avatar purple">{user.avatar}</div><strong>{user.username}</strong><small>Middleman account</small></div></aside><main className="mm-main"><header className="mm-topbar"><div><p className="eyebrow">MIDDLEMAN PORTAL</p><h1>{section}</h1></div><div className="mm-profile"><div className="avatar purple">{user.avatar}</div><div><strong>{user.username}</strong><small>Middleman account</small></div></div></header>{section === 'Overview' ? <><div className="mm-welcome"><p>Securely coordinate customer transactions from one workspace.</p><span className="mm-role">ROLE · MIDDLEMAN</span></div><div className="mm-stats">{[['Pending requests', stats.pendingRequests, 'Awaiting action'], ['Active transactions', stats.activeTransactions, 'In progress'], ['Completed transactions', stats.completedTransactions, 'All time'], ['Open disputes', stats.openDisputes, 'Need attention']].map(([label, value, description]) => <div className="mm-stat panel" key={label}><span>{label}</span><strong>{value}</strong><small>{description}</small></div>)}</div><div className="mm-panel panel"><div className="mm-panel-head"><div><p className="eyebrow">QUEUE</p><h2>Request management</h2></div><button className="primary-button">View requests →</button></div><div className="mm-empty"><span>⊙</span><strong>No requests assigned yet</strong><small>New customer middleman requests will appear here.</small></div></div></> : <div className="mm-panel panel"><p className="eyebrow">WORKSPACE</p><h2>{section}</h2><div className="mm-empty"><span>⌁</span><strong>This queue is clear</strong><small>Role-protected middleman tools will appear here as real transactions are assigned.</small></div></div>}</main></div>
}

export function MiddlemanProfile({ user }: { user: MiddlemanUser }) { return <div className="mm-panel panel mm-profile-page"><p className="eyebrow">MIDDLEMAN ACCOUNT</p><h1>Profile</h1><div className="mm-profile-hero"><div className="profile-avatar purple">{user.avatar}</div><div><h2>{user.username}</h2><p>{user.email}</p></div><span className="mm-role">ROLE · MIDDLEMAN</span></div><div className="mm-profile-details"><span>Account status</span><strong>Active</strong><span>Completed transactions</span><strong>0</strong><span>Average rating</span><strong>Not rated yet</strong><span>Member since</span><strong>{new Date(user.createdAt).toLocaleDateString()}</strong></div></div> }
